MODULEPATH_ROOT=/appl/spack/run/modulefiles/linux-centos7-x86_64
export MODULEPATH_ROOT=${MODULEPATH_ROOT}
export MODULEPATH=${MODULEPATH_ROOT}/Core:${MODULEPATH_ROOT}/Linux
export LMOD_COLORIZE=YES
export LMOD_PREPEND_BLOCK=NORMAL
